/**
 * This class represents a colony of houses.
 * 
 * @author Aviral Agrawal, Shubhi Jain, Sarthak Moorjani
 * @version September 3, 2018
 */
public class Colony {

    /**
     * This is an array of houses. In a colony we can have a maximum of 10 houses.
     * It is initialized in the constructor.
     */
    private House houses[];

    /**
     * This maintains the current number of houses in the colony.
     */
    private int numberOfHouses;

    /**
     * Constructor for objects of class Colony. Initializes the numberOfHouses to 0.
     */
    public Colony() {
        houses = new House[10];
        numberOfHouses = 0;
    }

    /**
     * Adds house to the colony if number of houses in the colony are less than 10.
     * 
     * @param house The house to be added in the colony
     * @return Returns true if house has been added successfully else return false.
     *         Note: Maximum houses in the colony cannot exceed 10.
     */
    public boolean addHouse(House house) {
        if (numberOfHouses >= 10)
            return false;
        houses[numberOfHouses++] = house;
        return true;

    }

    /**
     * Returns the number of houses in the colony.
     * 
     * @return Returns the number of houses in the colony.
     */
    public int getNumberOfHouses() {
        return numberOfHouses;
    }

    /**
     * For each house in the colony, you need to find the total number of good walls
     * in it and then return the sum of the number of good walls for every house.
     * For example, if the colony has 2 houses and house1 has 10 good walls and
     * house2 has 12 good walls, then you have to return 22.
     * 
     * @return Returns the total number of good walls in each house of the colony
     */
    public int goodWalls() {
        int good = 0;
        for (int i = 0; i < numberOfHouses; i++) {
            for (int j = 0; j < houses[i].getCountRooms(); j++) {
                for (int k = 0; k < 6; k++) {
                    if (houses[i].rooms[j].walls[k].getWallCondition() == 'g') {
                        good++;
                    }
                }
            }
        }
        return good;
    }

    /**
     * In this method you have to calculate the revenue that is generated by the
     * colony. So for each house in the colony, you need to find the revenue
     * generated by that house and then take the sum of all of them and return it.
     * For example, if there are 2 houses, and they generate 10 units and 20 units
     * of revenue respectively, then you should return 30.
     * 
     * @return Returns the sum of revenue generated by each house in the colony.
     */
    public int getRevenue() {
        int revenue = 0;
        for (int i = 0; i < numberOfHouses; i++) {
            revenue += houses[i].getRent();
        }
        return revenue;

    }
}
